### ISSUE TITLE
add options to pypi release

### ISSUE THREAD

**Issue by dhuckins** [getsentry/probot-release#25]
are pull requests still accepted?
would like to add config to the pypi release so you can pick what repository-url to hit

**Comment by jan-auer** [comment]
We have replaced probot-release with [craft](https://github.com/getsentry/craft). This project is not actively maintained anymore. I would suggest to check out craft, and if you like it, create a PR there. Cheers!

**Comment by dhuckins** [comment]
will check that out, thanks!
